_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 79
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 79
            "3":
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
batch_size:
    value: 512
epochs:
    value: 4000
learning_rate:
    value: 0.0001
samples_per_epoch:
    value: 100
