_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
batch_size:
    value: 256
epochs:
    value: 400
learning_rate:
    value: 0.001
samples_per_epoch:
    value: 20
